title = "Potential buffer overrun"
weight = 70
severity = "major"
verbose_name = "potential-buffer-overrun"
category = "security"
description = """
While writing data to a buffer, the program can overrun the buffer's boundary and overwrite adjacent memory locations.
These can either cause a crash if the memory region is inaccessible to the process for writing,
or in the worst case produce a vulnerability to overwrite parts of the memory with untrusted user code.

<!--more-->

Consider checking if there is such a bug. If it is intentional, ignore the issue in the panel or by using the `skipcq` flag.


## Examples

### Bad practice

```cpp
char dest[32] = {};
char* src = "this is probably a longer string that you expected to see?";
strcpy(dest, src);
```

### Recommended

```cpp
char dest[32] = {};
char* src = "this is probably a longer string that you expected to see?";
strncpy(dest, src, sizeof(dest));
```
"""
audit_required = true